name: ğŸ± Checker

on:
  pull_request:
    branches:
      - master

jobs:
  # ç¡®ä¿ PR ä¸­è¶…é“¾æ¥æœ‰æ•ˆæ€§
  markdown-link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          check-modified-files-only: 'yes'

  # æ£€æŸ¥ PR ä¸­è‹±æ–‡å•è¯æ‹¼å†™æ­£ç¡®æ€§
  spell-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install mispell
        run: |
          wget -O - -q https://git.io/misspell | sh -s -- -b .
      - name: Check
        run: |
          find -E . -regex ".*\.(ts|js|json)" -type f | xargs ./misspell -error
          find docs -type f | xargs ./misspell -error
          find . -type f -maxdepth 1 | xargs ./misspell -error
